import React from "react"
import Head from "next/head"
import Header from "./Header"
import Footer from "./Footer"

const Layout = ( {children, pagina} ) => {
    return (



      <div>

      <Head>
        <title>Redimidos - {pagina}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Sitio de noticias cristianas" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
       {children}
       <Footer />
      </div>
    )
  }

  export default Layout