import React from "react"
import Head from "next/head"
import Header from "./Header"
import Footer from "./Footer"

const Layout = ( {children, pagina} ) => {

  const title = `Redimidos - ${pagina}`;
    return (



      <div>

      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Sitio de noticias cristianas" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9577139226355545" crossorigin="anonymous"></script>
      </Head>

      <Header />
       {children}
       <Footer />
      </div>
    )
  }

  export default Layout